default_env: &default_env
  GITHUB_USERNAME: "ENCRYPTED github user name"
  GITHUB_REPOSITORY: "https://github.com/MonashAlexandria/alexandria"
  GITHUB_ACCESS_TOKEN: "Encrypted github token"
  GITHUB_STATUS_CONTEXT: "codebuild-ci"
  BUILD_PROJECT: "Alexandria"
  SLACK_HOOK_URL_CODE: ""
  SLACK_CHANNEL: "codebuild"
trigger:
  <<: *default_env