default_env: &default_env
  GITHUB_USERNAME: "KMS Encrypted"
  GITHUB_REPOSITORY: "https://github.com/MonashAlexandria/alexandria"
  GITHUB_ACCESS_TOKEN: "KMS Encrypted"
  GITHUB_STATUS_CONTEXT: "codebuild-ci-2"
  BUILD_PROJECT: "AlexandriaBuild"
  SLACK_HOOK_URL_CODE: "T091EMVT7/B6R7688DC/VuhYDK2WziVUYNIQup05Hzfm"
  SLACK_CHANNEL: "codebuild"
  KMS_KEY_ARN: "KMS used to encrypt Github username, created in aws-dev-kms project"
trigger:
  <<: *default_env
